clone:
  path: project

cache:
  mount:
    - /drone/.composer
    - /drone/src/project/web/app/themes/THEMENAME/node_modules

# List needed services here
compose:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  cache:
    image: redis
  web:
    image: devgeniem/wordpress-server
    pull: true
    environment:
      OVERRIDE_ROOT: /drone/src/project

      # Run processes as wordpress:web with these
      WP_UID: 100
      WP_GID: 101

      WP_REDIS_HOST: 127.0.0.1

      WP_ENV: testing

      WP_HOME: http://127.0.0.1
      WP_SITEURL: http://127.0.0.1

      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress

      SMTP_FROM: no-reply@wordpress.test
    extra_hosts:
      - "wordpress.test:127.0.0.1"

build:
  ##
  # Use this for building assets with different container
  ##
  frontend:
    image: devgeniem/node-assets-builder
    pull: true
    commands:
      - cd web/app/themes/THEMENAME/
      - npm install
      - ./node_modules/webpack/bin/webpack.js
  backend:
    image: devgeniem/wordpress-project-builder
    pull: true
    commands:
      # Enforce coding practises by style checks
      # TODO: This consumes more memory than we have available
      - ./scripts/code-style.sh

      # Install php dependencies
      - ./scripts/install.sh

      # Wait for mysql and Install WordPress
      - ./scripts/seed.sh

      # Run the tests
      - ./scripts/test.sh

    environment:
      # Allow better caching of composer packages
      COMPOSER_HOME: /drone/.composer

      # Allow all wrappers to work correctly and tell them the correct path
      PROJECT_ROOT: /drone/src/project
      WP_CORE: /drone/src/project/web/wp

      WP_REDIS_HOST: 127.0.0.1

      WP_ENV: testing

      WP_HOME: http://127.0.0.1
      WP_SITEURL: http://127.0.0.1

      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
    extra_hosts:
        - "wordpress.test:127.0.0.1"

##
# Change your slack url here
##

#notify:
#  slack:
#    webhook_url: YOUR_SLACK_URL_HERE
#    channel: drone
#    username: Drone CI
#    template: |
#      {{#success build.status}}
#        <{{ repo.link_url }}|{{ repo.full_name }}>: {{ build.author }} pushed succesfully to {{ build.branch }} branch.
#      {{else}}
#        <{{ repo.link_url }}|{{ repo.full_name }}>: {{ build.author }} broke {{ build.branch }} branch :(. <{{ build.link_url }}|See results>
#      {{/success}}

##
# Deploy to Geniem cluster
##

#deploy:
#  webhook:
#    debug: true
#    method: PUT
#    urls:
#      - http://172.17.0.1/geniem-api/v1/deploy/
#    content_type: application/json
#    template: '{"name": "{{repo.name}}", "git_branch": "{{ build.branch }}", "commit": "{{build.commit}}", "status": "{{build.status}}" }'
