sudo: false
language: php
php:
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

script:
  # Check project with php codesniffer
  - phpcs --standard=./phpcs.xml -n -p --report=summary .
  # Check that composer is valid and installs correctly
  - composer install -o --prefer-dist --no-interaction
