sudo: false
language: php
php:
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

  # Install phpcs
  - composer global require "squizlabs/php_codesniffer=*"

script:
  # Check project with php codesniffer
  - ~/.composer/vendor/bin/phpcs --standard=./phpcs.xml -n -p --report=summary .

  # Check that composer is valid and installs correctly
  - composer install -o --prefer-dist --no-interaction
