sudo: false
language: php
php:
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - $HOME/wpcs
    - vendor


before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

  # Install phpcs with wp-coding-standards
  - composer create-project wp-coding-standards/wpcs:dev-master --no-dev $HOME/wpcs

script:
  # Check project with php codesniffer
  - ~/wpcs/vendor/bin/phpcs --standard=./phpcs.xml -n -p --report=summary .

  # Check that composer is valid and installs correctly
  - composer install -o --prefer-dist --no-interaction
